baseURL = "https://hacktoberfest.scot"
disableLanguages = ['fr']
disqusShortname = ""
paginate = "6"
summaryLength = "15"
theme = "meghna-hugo"
title = "Hacktoberfest Scotland"
[Languages.en]
contentDir = "content/english"
copyright = "Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Gethugothemes](https://gethugothemes.com)"
home = "Home"
languageCode = "en-us"
languageName = "En"
weight = 1
[Languages.fr]
contentDir = "content/french"
copyright = "Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Gethugothemes](https://gethugothemes.com)"
home = "Accueil"
languageCode = "fr-fr"
languageName = "Fr"
weight = 2
[[menu.main]]
name = "REGISTER!"
pre = "#"
url = "cta"
weight = "1"
[[menu.main]]
name = "speakers"
pre = "#"
url = "speakers"
weight = "2"
[[menu.main]]
name = "agenda"
pre = "#"
url = "agenda"
weight = "3"
[[menu.main]]
name = "rooms"
pre = "#"
url = "channels"
weight = "4"
[[menu.main]]
name = "organisers"
pre = "#"
url = "organisers"
weight = "5"
[params]
author = "Hacktoberfest Scotland"
description = "Hacktoberfest Scotland 2020"
google_analytics_id = ""
logo = "images/hacktoberfest-scotland-logo.png"
post_share = false
[params.cookies]
enable = false
expire_days = 2
[params.map]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Anaheim|Quattrocento+Sans:400,700&display=swap"
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/lazy-load/lozad.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"

[[params.plugins.css]]
link = "https://fonts.googleapis.com/css2?family=Fira+Sans&family=Roboto&display=swap"

[params.preloader]
enable = false
preloader = "images/logo.png"